# Site settings
title: Notes
#email: a.yukhanov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Notes on software development
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  alyukhan

# Build settings
markdown: kramdown
